---
title: "DA values"
author: "David Navega, João Coelho"
date: "4 de Agosto de 2015"
output: html_document
---

```{r, include=FALSE, echo=FALSE}
library(knitr)
# main file for Gonçalves et al. Skeletal Mass Regression Project
#
# Keypoints to address in this project:
#
# Regression model complexity, assumptions, peer-acceptance
# Missing value handling
# Bilateral values handling
# Colinearity, colinearity everywhere...

# read data.frame
df <- read.csv('./data/massReg-processed.csv')

# split into different data.frame structures to ease up data analysis
bio <- df[, c("SEX","AGE")] # biological profile data, SEX and AGE
total.mass <- df[, "TOTAL.MASS"] # target variable, total skeletal mass
longbones.l <- df[, c("HMR.L","FMR.L")] # left femur and humerus
clavicles <- df[, 5:6] 
metacarpals <- df[, 7:16]
patellas <- df[, 17:18]
tarsals <- df[, 19:32]
metatarsals <- df[, 33:42]
# variable names
var.names.lr <- c(colnames(clavicles),colnames(metacarpals),colnames(patellas),
                  colnames(tarsals),colnames(metatarsals))
var.names.idx <- grep(pattern = ".L",var.names.lr,fixed = TRUE)
var.names <- gsub(pattern = ".L", replacement = "", 
                  x = var.names.lr[var.names.idx],fixed = TRUE)

## Handling bilateral values
# auxiliar function
bilateral.asymmetry <- function (m, sig = 0.01) {
  # Test for bilateral asymmetry using relative directional asymmetry and 
  # Wilcoxon signed ranks test.
  #
  # m: a n-by-2 matrix contrain antimeres of a bilateral bone
  # note: matrix is order from left to right
  
  idx <- complete.cases(m)
  m.aux <- m[idx,]
  wcx.paired <- wilcox.test(x = m.aux[,1],y = m.aux[,2], exact = F, paired=T)
  if(wcx.paired$p.value <= sig){
    asymm <- TRUE 
  }else{
    asymm <- FALSE
  }
  da <- ((m.aux[,2]-m.aux[,1])/apply(m.aux, 1, mean))*100
  da <- median(da)
  
  res <- list(DA = da, statistic= as.numeric(wcx.paired$statistic), 
              p.value = wcx.paired$p.value, n = NROW(m.aux), asymm = asymm)
  return(res)
}

# testing for bilateral asymmetry
result <- vector()
result <- rbind(result, unlist(bilateral.asymmetry(clavicles)))
for(i in seq(1,NCOL(metacarpals),2)){
  m <- cbind(metacarpals[,i],metacarpals[,i+1])
  result <- rbind(result, unlist(bilateral.asymmetry(m)))
}
result <- rbind(result, unlist(bilateral.asymmetry(patellas)))
for(i in seq(1,NCOL(tarsals),2)){
  m <- cbind(tarsals[,i],tarsals[,i+1])
  result <- rbind(result, unlist(bilateral.asymmetry(m)))
}
for(i in seq(1,NCOL(metatarsals),2)){
  m <- cbind(metatarsals[,i],metatarsals[,i+1])
  result <- rbind(result, unlist(bilateral.asymmetry(m)))
}
rownames(result) <- var.names

```


```{r}
kable(result)
```

